### ISSUE TITLE
Can't open Peppymeter

### ISSUE THREAD

**Issue by me12ke** [project-owner/PeppyMeter.doc#1]
Hi, I downloaded the Pappy Meter according to the instructions. Alsa mixer works, but when I try to start the Pappy Meter via python3 Peppymeter / peppymeter.py I only get some error messages. Can someone help me?

This are my Error Messages:

pygame 1.9.4.post1
Hello from the pygame community. https://www.pygame.org/contribute.html
Traceback (most recent call last):
  File "PeppyMeter/peppymeter.py", line 234, in <module>
    pm = Peppymeter(standalone=True)
  File "PeppyMeter/peppymeter.py", line 60, in __init__
    parser = ConfigFileParser(base_path)
  File "/home/pi/PeppyMeter/configfileparser.py", line 145, in __init__
    self.meter_config[METER] = c.get(CURRENT, METER)
  File "/usr/lib/python3.7/configparser.py", line 780, in get
    d = self._unify_values(section, vars)
  File "/usr/lib/python3.7/configparser.py", line 1146, in _unify_values
    raise NoSectionError(section) from None
configparser.NoSectionError: No section: 'current'

**Comment by project-owner** [comment]
Hi,

Please start the program from the folder where peppymeter.py is located. So instead of
```
python3 Peppymeter/peppymeter.py
```
try this:
```
cd Peppymeter
python3 peppymeter.py
```
Best regards

**Comment by me12ke** [comment]
Thanks but this also don't worked 


pi@raspberrypi:~ $ cd Peppymeter
bash: cd: Peppymeter: No such file or directory
pi@raspberrypi:~ $ python3 peppymeter.py
python3: can't open file 'peppymeter.py': [Errno 2] No such file or directory

**Comment by project-owner** [comment]
It should be the folder where you installed the program. Usually it's PeppyMeter if you didn't rename it.
```
cd PeppyMeter
```

**Comment by me12ke** [comment]
The trouble is that I didn't rename it but it still doesn't work

**Comment by project-owner** [comment]
Can you run the following command after 'cd PeppyMeter' and show the output:
```
pwd
```

**Comment by project-owner** [comment]
Please make sure that you type exactly PeppyMeter with capital 'M'

**Comment by me12ke** [comment]
Yes. 

pi@raspberrypi:~ $ cd PeppyMeter
pi@raspberrypi:~/PeppyMeter $ pwd
/home/pi/PeppyMeter
pi@raspberrypi:~/PeppyMeter $

**Comment by me12ke** [comment]
No, it don't work. If I start the programm than came the error code from my first massage.

**Comment by project-owner** [comment]
OK, let's assume that you are in the /home/pi/PeppyMeter folder and when you start there is that exception.
Have you modified the file /home/pi/PeppyMeter/config.txt?

**Comment by me12ke** [comment]
Yes, I changed it according to the instructions. I thought you had to ...

**Comment by me12ke** [comment]
But even if I copy the original config file into it, it shows me the same error and I just don't know what to do with it.

**Comment by project-owner** [comment]
Can you just run the following commands and see if it works?
```
cd /home/pi
rm -rf PeppyMeter
git clone https://github.com/project-owner/PeppyMeter.git
cd PeppyMeter
python3 peppymeter.py
```

**Comment by me12ke** [comment]
Okay, now at least the program opens, only when I run something with a player, it does not move graphically and it writes something to me like:

libpng warning: iCCP: known incorrect sRGB profile

**Comment by me12ke** [comment]
I tried to play an mp3 file via the VLC player and also connected the VLC player via the config file, but the pointer doesn't move a bit. Even if you connect a microphone, it doesn't move.

**Comment by kolya-povalyaev** [comment]
Hello, I installed pygame version 1.9.4, but still the needles don't move.
