### ISSUE TITLE
WebServer Error: 405: Method Not Allowed

### ISSUE THREAD

**Issue by dubaleeiro** [project-owner/PeppyMeter.doc#10]
Hi,
I am trying to get the VU Meters with the WebServer based on audio from Shairport-Sync  but when I access the adress of my raspberry pi I get the following error in the webpage:

`405: Method Not Allowed`

What could be the reason for that? Thanks for any help... !

**Comment by project-owner** [comment]
Hi,

It's not clear what you are trying to do. Could you explain your configuration? How did you configure PeppyMeter? How do you want to observe a volume data?

Best regards

**Comment by dubaleeiro** [comment]
Hi, thanks for your fast response !

I want to use the `peppyalsa` and `PeppyMeter` libraries to drive a Spectrum Analyzer out of a NeoPixel LED strip, based on a audio streaming from Shairport-sync in a Raspberry Pi Zero and a HifiBerry AMP2 hat.

My relevant configuration files are (please tell me if more info is needed):
**/etc/asound.conf:**
`pcm.!default {
        type plug
        slave.pcm "softvol_and_peppyalsa"
}

ctl.!default {
        type hw
        card 0
}

pcm.peppyalsa {
        type meter
        slave.pcm "hw:0,0"
        scopes.0 peppyalsa
}

pcm.softvol_and_peppyalsa {
        type softvol
        slave.pcm "peppyalsa"
        control {
                name "Digital"
                card 0
        }
}

pcm_scope.peppyalsa {
        type peppyalsa
        decay_ms 400
        meter "/home/pi/myfifo"
        meter_max 100
        meter_show 0
        spectrum "/home/pi/myfifosa"
        spectrum_max 100
        spectrum_size 30
        logarithmic_frequency 0
        logarithmic_amplitude 1
        smoothing_factor 20
        window 3
}

pcm_scope_type.peppyalsa {
        lib /usr/local/lib/libpeppyalsa.so
}

pcm.dsp0 peppyalsa`

**/home/pi/PeppyMeter/config.txt:**

`[current]
meter = random
random.meter.interval = 20
meter.size = medium
screen.width =
screen.height =
exit.on.touch = False
output.display = False
output.serial = False
output.i2c = False
output.pwm = False
output.http = True
use.logging = False
use.cache = True
frame.rate = 30

[sdl.env]
framebuffer.device = /dev/fb1
mouse.device = /dev/input/touchscreen
mouse.driver = TSLIB
mouse.enabled = True
video.driver = dummy
video.display = :0
double.buffer = True
no.frame = False

[serial.interface]
device.name = /dev/serial0
baud.rate = 9600
include.time = False
update.period = 0.1

[i2c.interface]
port = 1
left.channel.address = 0x21
right.channel.address = 0x20
output.size = 10
update.period = 0.1

[pwm.interface]
frequency = 500
gpio.pin.left = 24
gpio.pin.right = 25
update.period = 0.1

[http.interface]
target.url = http://localhost:8000/vumeter
update.period = 0.033

[web.server]
http.port = 8000

[data.source]
type = http
polling.interval = 0.033
pipe.name = /home/pi/myfifo
volume.constant = 80.0
volume.min = 0.0
volume.max = 100.0
volume.max.in.pipe = 100.0
step = 6
mono.algorithm = average
stereo.algorithm = new
smooth.buffer.size = 4

[bar]
meter.type = linear
channels = 2
ui.refresh.period = 0.033
bgr.filename = bar-bgr.png
indicator.filename = bar-indicator.png
left.x = 130
left.y = 113
right.x = 130
right.y = 178
position.regular = 11
position.overload = 3
step.width.regular = 19
step.width.overload = 25
meter.x = 0
meter.y = 0
screen.bgr =

[blue]
meter.type = circular
channels = 1
ui.refresh.period = 0.033
bgr.filename = blue-bgr.png
fgr.filename = blue-fgr.png
indicator.filename = blue-needle.png
steps.per.degree = 2
start.angle = 45
stop.angle = -45
distance = 183
mono.origin.x = 238
mono.origin.y = 380
meter.x = 0
meter.y = 0
screen.bgr =

[vintage]
meter.type = circular
channels = 2
ui.refresh.period = 0.033
bgr.filename = vintage-bgr.png
fgr.filename = vintage-fgr.png
indicator.filename = vintage-needle.png
steps.per.degree = 2
start.angle = 45
stop.angle = -45
distance = 54
left.origin.x = 129
left.origin.y = 217
right.origin.x = 349
right.origin.y = 217
meter.x = 0
meter.y = 0
screen.bgr =
`
Thanks !

**Comment by project-owner** [comment]
OK, when you enable HTTP output in the PeppyMeter it will send HTTP requests to the web address defined in this parameter in the config.txt:
```
[http.interface]
target.url = http://localhost:8000/vumeter
```
In this case the web server where meter sends requests is a 'localhost'. But I think there is no any web server running on your Pi. So, nobody can handle those requests. You can start another PeppyMeter on any other host. You can configure its data source as 'http'. For such configuration you need to install Tornado web server. All this is explained here:
https://github.com/project-owner/PeppyMeter.doc/wiki/Web-Server
https://github.com/project-owner/PeppyMeter.doc/wiki/Inputs

When you complete all these steps you can send volume level signal using PeppyMeter from one machine to another. That's the main idea behind this implementation in PeppyMeter. I'm not sure that this is what you need though. Also meter doesn't send spectrum signal over HTTP, only volume level.

Best regards

**Comment by dubaleeiro** [comment]
Hi, I had followed the above steps for tornado installation and WebServer configuration.

still I don’t get any volume information, when I access the indicates address based on my IP I get the following error message:

ˋ405: Method Not Allowedˋ

**Comment by project-owner** [comment]
Do you want to see volume data in browser? There is no Web UI in PeppyMeter. You start Tornado web server to receive HTTP requests with volume data. But there is no any logic in the meter to provide that data to a web browser.
Sorry, maybe I still don't understand what you are trying to achieve.

Best regards

**Comment by dubaleeiro** [comment]
Hi,
Maybe I did not understand how these http requests should work… I am sorry for that.
May I ask you then a different question? Which is the best way to use these great libraries ˋˋˋpeppyalsaˋˋˋ and ˋˋˋPeppyMeterˋˋˋ to extract audio information (volume for instance) to a linear spectrum analizer made of NeoPixel LEDs? Thanks a lot for your support and patience…

**Comment by project-owner** [comment]
Hi,

PeppyMeter doesn't provide spectrum analyzer functionality. You can get spectrum signal from the 'peppyalsa' plugin but you need to write your own client to handle it. You need to write program (in any language) which will read data provided by 'peppyalsa' from the named pipe and send it to neopixel LEDs. Here is a similar project but for volume data:
https://forum-raspberrypi.de/forum/thread/38115-peppy-webradio/?postID=510110#post510110

Best regards

**Comment by dubaleeiro** [comment]
Hi,
I think I finally understood the current capabilities of PeppyMeter. I maneged to make a "VU-Meter" using a NeoPixels LED strip based on volume data `PeppyMeter` sends to the serial port !

Now I would like to setup a `systemmd` service but I am getting the following error:

 ```
● vu-meter.service - VU Meter based on PeppyMeter aplication
     Loaded: loaded (/etc/systemd/system/vu-meter.service; enabled; vendor preset: enabled)
     Active: failed (Result: exit-code) since Fri 2021-12-10 17:22:24 GMT; 36s ago
    Process: 1476 ExecStart=/usr/bin/python3 /home/pi/PeppyMeter/peppymeter.py (code=exited, status=1/FAILURE)
   Main PID: 1476 (code=exited, status=1/FAILURE)
        CPU: 6.344s

Dec 10 17:22:23 comitup-175 python3[1476]:   File "/home/pi/PeppyMeter/configfileparser.py", line 160, in __init__
Dec 10 17:22:23 comitup-175 python3[1476]:     self.meter_config[METER] = c.get(CURRENT, METER)
Dec 10 17:22:23 comitup-175 python3[1476]:   File "/usr/lib/python3.9/configparser.py", line 781, in get
Dec 10 17:22:23 comitup-175 python3[1476]:     d = self._unify_values(section, vars)
Dec 10 17:22:23 comitup-175 python3[1476]:   File "/usr/lib/python3.9/configparser.py", line 1149, in _unify_values
Dec 10 17:22:23 comitup-175 python3[1476]:     raise NoSectionError(section) from None
Dec 10 17:22:23 comitup-175 python3[1476]: configparser.NoSectionError: No section: 'current'
Dec 10 17:22:24 comitup-175 systemd[1]: vu-meter.service: Main process exited, code=exited, status=1/FAILURE
Dec 10 17:22:24 comitup-175 systemd[1]: vu-meter.service: Failed with result 'exit-code'.
Dec 10 17:22:24 comitup-175 systemd[1]: vu-meter.service: Consumed 6.344s CPU time.
```

The application is working perfectly in command line with a `python3 peppymeter.py` command. Any hints about what could be causing this problem, please? Thanks !

This is the service file:
```
Unit]
Description=VU Meter based on PeppyMeter aplication
After=multi-user.target

[Service]
User=pi
Group=pi
ExecStart=/usr/bin/python3 /home/pi/PeppyMeter/peppymeter.py

[Install]
WantedBy=multi-user.target
```

**Comment by project-owner** [comment]
Hi, you need to start the program from the folder /home/pi/PeppyMeter. So first you need to change folder:
cd /home/pi/PeppyMeter
and then start the program:
/usr/bin/python3 peppymeter.py

Another way is to start the program from the file: /etc/rc.local:
su pi -c 'cd /home/pi/PeppyMeter; openvt -s -- python3 peppymeter.py'
In this case it will be also started during Pi startup process.

Best regards

**Comment by dubaleeiro** [comment]
Hi,
Thanks for the quick reply !
I have just found out that the following line in the service file also does the work:

```
[Service]
WorkingDirectory=/full/path/to/th/script
```
