### ISSUE TITLE
Not an issue just a question. 

### ISSUE THREAD

**Issue by thalk84** [project-owner/PeppyMeter.doc#11]
Please excuse any ignorance is my question I apologize in advance. That being said is there anyway to use a different input method say if I want to use the analog out from a Blue sound Node 2i feed into the pi(how I'm not sure about that either) to then display the meters? If that's not possible is there another input method into the pi coming from an external source to display on a 7 in touch screen connected to said pi. If not do you happen to know of a way to make something like this happen. I do ALOT of pi tinkering and wouldn't ask if I wasn't at my witts ends in terms of research and previous attempts, actually this is my first ever git question! I appreciate very much so any help usually after lots of research and breaking of things I can get most projects up and going but this one maybe the end of me!

**Comment by project-owner** [comment]
Hi,

Currently the PeppyMeter supports only one type of input - from the named pipe. The signal in the named pipe should be provided by the 'peppyalsa' plugin.

You can provide the input from Analog-to-Digital Converter (ADC). Using this kind of input it could be possible to connect any device with analog output. So, the idea is to use any appropriate ADC and write the simple program/driver in Python. That driver could just periodically read data from the ADC and send it to the named pipe in the same format which is currently expected by the PeppyMeter. This way there is no need to modify the PeppyMeter code.

There are many ADCs on the market which could be used for this functionality. Here are just some examples which also include the code in Python:
https://www.adafruit.com/product/1085
https://www.adafruit.com/product/1083
https://www.adafruit.com/product/856
https://learn.adafruit.com/reading-a-analog-in-and-controlling-audio-volume-with-the-raspberry-pi?view=all

Another question to which should be answered - how should the ADC be connected to the audio output of the audio device (e.g. linear output)? Do you just directly connect to the audio device output (e.g. linear output) or do you need to use for this connection some passive components (resistors and capacitors) to eliminate the impact on the output?

Please let me know if will be able to connect your audio device to the PeppyMeter this way.

Best regards

**Comment by thalk84** [comment]
Good morning,

Thank you so very much for the fast response. So a lot of what you said is
a bit over my head but after checking some of the links you sent it looks
like something that i can gain understanding of with a bit of research
paired with some trial and error. So I totally understand that the pi has
no analog input but that did not cross my mind when I sent the original
question. As i am typing this your email is actually starting to make much
more sense and seems to be a lot simpler than what I thought upon my
initial reading. First question when you say linear output from the audio
device I assume you mean line level ie. RCA output? I am currently using
this RCA output from the audio device to feed a set of powered speakers. I
could split this signal and have it not only feed the speakers but the ADC
as well if that makes sense. I assume we are on the same page so far. At
this point I don't understand your next question/suggestion: using passive
components. Are you saying these would be needed to stop negative effects
on the speakers? If the signal to the ADC is parallel to the signal for the
speakers speakers and not in line or in front of the speakers signal in any
way could there still be a negative impact on the signal to the speakers?
Last I would need to address writing the python script for the ADC. I have
some python knowledge but not enough to write said program. I
definitely can figure out the physical connections concerning the ADC and
pi, I think I can anyway lol. And I may actually have a ADC on hand that
may work. So at this point I am going to find that ADC and figure out
getting it talking to the pi while I wait on your response. If everything I
have said so far is ok with help on the script I could possibly have this
up and going fairly soon!

Eagerly waiting you response,
Thomas

**Comment by thalk84** [comment]
What about using something like a MAX4466
https://learn.adafruit.com/adafruit-microphone-amplifier-breakout?view=all
. This could theoretically pick up the audio from the speakers and convert
it to the peppy program no? I know it will be no where as accurate but just
a thought.

**Comment by project-owner** [comment]
Hi Thomas,

Yes I meant 'line output' not 'linear output'. And that's what you usually use to connect your audio source and amplifier (or powered speakers) through RCA connectors. 
As far as I remember the voltage in that line is about1 V max:
https://geoffthegreygeek.com/audio-levels/
https://en.wikipedia.org/wiki/Line_level

I've never done that so you need to clarify if just splitting that line output and connecting ADC to that line directly is the way to go. I suspect that it can affect the signal which go to the amplifier and/or powered speakers.
Therefore some kind of additional components should be connected between line output and ADC. More likely it should be passive components (resistors and capacitors). I've never done that so I don't know the details.
If you will buy the ADC on the Adafruit web site you can ask this kind of question on their forum.

Depending on the ADC type it can be connected to Pi either through I2C or SPI interfaces. There are many examples on the Adafruit web site and the Internet how to handle those interfaces from Python. It's not that complicated.

If you don't mind to show in VU Meter not only audio level but also environment noise and the level of your voice then you can use the approach with microphone and amplifier too.

Best regards

**Comment by thalk84** [comment]
I am going to order the adc right now. In the meantime can you tell me how
to interface the mic approach ?

Much appreciated,

**Comment by project-owner** [comment]
I believe you still need to convert analog signal which comes from the mic amplifier to digital signal using ADC. In that Adafruit example I think they use ADC from the Arduino micro-controller.

**Comment by thalk84** [comment]
You are totally right. I just figured that out so I am attempting to use a
braincraft hat which has dual mics. Watcha think?

https://learn.adafruit.com/adafruit-braincraft-hat-easy-machine-learning-for-raspberry-pi

**Comment by project-owner** [comment]
That HAT is pretty expensive for the task of showing audio volume level. Also I don't know how to get volume level from that board. You will need to figure that out. It's up to you which way to go.

**Comment by thalk84** [comment]
I already had the hat on hand. Ive been working on it for a while now and when i start pepper i get :

pi@raspberrypi:~/PeppyMeter $ python3 peppymeter.py
pygame 1.9.4.post1
Hello from the pygame community. https://www.pygame.org/contribute.html
Traceback (most recent call last):
  File "peppymeter.py", line 290, in <module>
    pm.init_display()
  File "peppymeter.py", line 150, in init_display
    pygame.display.init()
pygame.error: Unable to open /dev/fb1
^\Segmentation fault


any help

**Comment by project-owner** [comment]
You can try to use /dev/fb0 by changing the configuration file:
https://github.com/project-owner/PeppyMeter/blob/914ebcabe037df5854ad2ac0939084b816857c5b/config.txt#L18
