### ISSUE TITLE
PeppyMeter Working via GPIO, Not HDMI, peppyalsa-client Working

### ISSUE THREAD

**Issue by malanmurphy** [project-owner/PeppyMeter.doc#12]
Hardware: rp4
Screen: ElecLab 7.4 HDMI Touchscreen
Software: Bullseye 32-bit

Similar to this issue -- https://github.com/project-owner/PeppyMeter.doc/issues/8 -- I'm able to run PeppyMeter without issue on a 3.5 TFT via a GPIO connection, but when trying the same setup with an HDMI monitor (on HDMI port 0), PeppyMeter doesn't register any movement. I've confirmed what I believe is everything is working fine with peppyalsa by setting `meter_show 1` in /etc/asound.conf (see below for output from terminal): when I play a wav file directly I'm seeing levels, and when I pipe music to the loopback via Roon and run `peppyalsa-client` I'm seeing levels as expected. But when I run PeppyMeter there's no movement. I've tested setting `double.buffer = False` as suggested in the above linked issue but no luck, same result. I've copied both /etc/asound.conf and my PeppyMeter config.txt files below. 

Is there something I'm missing with the HDMI output? 

$ ./peppyalsa-client                                         
L: =====================================================                       
R: ====================================================                        

$ aplay -D peppyalsa ~/piano2.wav 
Playing WAVE '/home/pi/piano2.wav' : Signed 16 bit Little Endian, Rate 48000 Hz, Stereo
L: ============                                                                
R: ===============                                                             

`/etc/asound.conf`

pcm.!default {
    type plug
    slave.pcm "softvol_and_peppyalsa"
}

ctl.!default {
    type hw
    card 0
}

pcm.peppyalsa {
    type meter
    slave.pcm "hw:0,0"
    scopes.0 peppyalsa
}

pcm.softvol_and_peppyalsa {
    type softvol
    slave.pcm "peppyalsa"
    control {
        name "PCM"
        card 0
    }
}

pcm_scope.peppyalsa {
    type peppyalsa
    decay_ms 400
    meter "/home/pi/myfifo"
    meter_max 100
    meter_show 1
    spectrum "/home/pi/myfifosa"
    spectrum_max 100
    spectrum_size 30
    logarithmic_frequency 0
    logarithmic_amplitude 1
    smoothing_factor 20
    window 3
}

pcm_scope_type.peppyalsa {
    lib /usr/local/lib/libpeppyalsa.so
}

pcm.dsp0 peppyalsa

---

`config.txt`

[current]
meter = white-red, blue-2, vertical-circular, emerald, red, vintage, gold
random.meter.interval = 60
meter.size = large
screen.width = 
screen.height = 
exit.on.touch = True
stop.display.on.touch = True
output.display = True
output.serial = False
output.i2c = False
output.pwm = False
output.http = False
use.logging = False
use.cache = True
frame.rate = 30

[sdl.env]
framebuffer.device = /dev/fb1
mouse.device = /dev/input/touchscreen
mouse.driver = TSLIB
mouse.enabled = True
video.driver = dummy
video.display = :0
double.buffer = False
no.frame = True

[serial.interface]
device.name = /dev/serial0
baud.rate = 9600
include.time = False
update.period = 0.1

[i2c.interface]
port = 1
left.channel.address = 0x21
right.channel.address = 0x20
output.size = 10
update.period = 0.1

[pwm.interface]
frequency = 500
gpio.pin.left = 24
gpio.pin.right = 25
update.period = 0.1

[http.interface]
target.url = http://localhost:8000/vumeter
update.period = 0.033

[web.server]
http.port = 8001

[data.source]
type = pipe
polling.interval = 0.033
pipe.name = /home/pi/myfifo
volume.constant = 80.0
volume.min = 0.0
volume.max = 100.0
volume.max.in.pipe = 100.0
step = 6
mono.algorithm = average
stereo.algorithm = new
smooth.buffer.size = 4

**Comment by malanmurphy** [comment]
Another interesting detail: even though I have the following set: 

exit.on.touch = True
stop.display.on.touch = True

Nothing happens when I touch the screen. The touchscreen is working great for any other app, just doesn't exit PeppyMeter when I touch the screen. Could it be related?

**Comment by project-owner** [comment]
Please make sure that you really have devices specified in the config.txt:
 /dev/fb1 - for display
/dev/input/touchscreen - for touch screen

Best regards

**Comment by malanmurphy** [comment]
Thanks for the quick reply and good catch. I didn't have /dev/fb1 so I changed config.txt to /dev/fb0, but same result: PeppyMeter loads fine in X, cycles through the meters I have config'd, but no needle movement. I've verified that /dev/fb0 is the correct device using `fbi` and it's working as expected. 

I'll circle back to the touchscreen dev issue once I get input into PeppyMeter working. :)

**Comment by project-owner** [comment]
Today I've fixed one critical PeppyMeter bug. Please try the latest code with bug fix.

Best regards

**Comment by malanmurphy** [comment]
That did it! It's working perfectly now. :) Thanks so much for looking into this and for the quick update, very cool and really appreciated!
