### ISSUE TITLE
Error when starting peppyalsa

### ISSUE THREAD

**Issue by kolya-povalyaev** [project-owner/PeppyMeter.doc#13]
Hello, could you help me?
After installing peppyalsa, an error occurs when trying to run peppyalsa to verify that peppyalsa is installed correctly :

aplay -D peppyalsa 05.wav
Playing WAVE '05.wav' : Signed 16 bit Little Endian, Rate 44100 Hz, Stereo
Floating point exception (core dumped)

at the same time , when

aplay -D hw:0,0 05.wav
Playing WAVE '05.wav' : Signed 16 bit Little Endian, Rate 44100 Hz, Stereo

That's all right

**Comment by project-owner** [comment]
Hi, where do you run the plugin - which platform (Raspberry Pi or PC), which OS, 32 or 64-bit? Was the plugin build successful, what is the content of your .asoundrc file?

**Comment by kolya-povalyaev** [comment]
Hello, PC platform ,

Kernel: 4.15.0-213-generic x86_64 bits: 64 Ubuntu 18.04.6 LTS

There were no errors when building the plugin

the contents of the asound.conf file

pcm.!default {
    type plug
    slave.pcm "softvol_and_peppyalsa"
}

ctl.!default {
    type hw
    card 0
}

pcm.peppyalsa {
    type meter
    slave.pcm "hw:0,0"
    scopes.0 peppyalsa
}

pcm.softvol_and_peppyalsa {
    type softvol
    slave.pcm "peppyalsa"
    control {
        name "PCM"
        card 0
    }
}

pcm_scope.peppyalsa {
    type peppyalsa
    decay_ms 400
    meter "/tmp/myfifo"
    meter_max 100
    meter_show 1
    spectrum "/tmp/myfifosa"
    spectrum_max 100
    spectrum_size 30
    logarithmic_frequency 0
    logarithmic_amplitude 1
    smoothing_factor 20
    window 3
}

pcm_scope_type.peppyalsa {
    lib /usr/local/lib/libpeppyalsa.so
}

pcm.dsp0 peppyalsa


the /tmp/mififo buffer is installed
but even with the default one ("/home/pi/myfifo"), the problem is the same.

**Comment by project-owner** [comment]
I'd recommend to ask the question about PC build on Volumio forum:
https://community.volumio.com/t/project-with-peppymeter-screensaver-plugin-for-volumio-v2-9xx-and-3-0xx-buster/45862/7
As far as I remember someone reported about successful usage of the PeppyMeter on PC.

**Comment by project-owner** [comment]
Here is the dedicated thread:
https://community.volumio.com/t/volumio-x86-peppymeter/57697

**Comment by kolya-povalyaev** [comment]
Hello, the fact is that everything is installed and working on "volumio", but I want to install peppymeter on a clean ubuntu 64bit, but there was a problem installing peppyalsa.

**Comment by project-owner** [comment]
Hi, what is the problem? Which files are empty? Have you installed all dependencies? Maybe the last command 'sudo make install' didn't copy files into correct folders?

**Comment by kolya-povalyaev** [comment]
Hello, here is a list of empty files (0 bytes)

aclocal.m4
AUTHORS
config.log
config.status
configure
configure.ac
libpeppyalsa.la
libtool
LICENSE
Makefile
Makefile.am
Makefile.in
NEWS
README
setup.sh

**Comment by kolya-povalyaev** [comment]
At the same time, after aplay -L displays a complete list of sound cards and peppyalsa and softvol_and_peppyalsa are there.

**Comment by project-owner** [comment]
I don't know if build process on Ubuntu is different from Debian.
Did you see any errors when you installed the following dependencies?
```
build-essential autoconf automake libtool libasound2-dev libfftw3-dev
```
Any errors after these commands?
```
aclocal && libtoolize
autoconf && automake --add-missing
./configure && make
sudo make install
```
What's the filesize of this file /usr/local/lib/libpeppyalsa.so ?

**Comment by kolya-povalyaev** [comment]
Hello, there were no errors when installing dependencies, there would be no errors after the listed conades either.
after the command
./configure && make there were warnings

the file in the specified directory is libpeppyalsa.so.0.0.0
. its size is 72.9kB

**Comment by project-owner** [comment]
Hmm, everything looks OK. The only confusing thing is that the peppyalsa doesn't use float numbers for VU Meter functionality.
Can you remove spectrum analyzer section from the configuration and see if that makes any difference?
```
spectrum "/tmp/myfifosa"
spectrum_max 100
spectrum_size 30
logarithmic_frequency 0
logarithmic_amplitude 1
smoothing_factor 20
window 3
```

**Comment by kolya-povalyaev** [comment]
hello, I have only deleted

logarithmic_frequency 0
logarithmic_amplitude 1
smoothing_factor 20
window 3

and the peppyalsa driver is working.Thanks
But this is only part of the problem,
at first I installed peppymeter completely, but it did not work, the screensaver itself started, but the needles did not move.I started checking the peppyalsa driver, but it didn't work, I tried to figure it out for a long time, but I couldn't, and then I wrote to you here.

Could you help me with this problem as well?

**Comment by project-owner** [comment]
I've found that issue recently while testing the Peppy Player on a new version of OS and Pygame 2 library (used for UI). The dynamic screen update doesn't work anymore. It doesn't work for track time, VU Meter etc. It looks like the new version of Pygame is using new display driver KMSDRM. Screen updates don't work properly for that combination. I'm still trying to find a solution for that issue...

**Comment by kolya-povalyaev** [comment]
Hello, I installed pygame version 1.9.4, but still the needles don't move.

**Comment by project-owner** [comment]
I've fixed the issue. Now PeppyMeter works on the system where it didn't work before. I need to make one more change for the Volumio team. Then I'll make a new release. I hope to do that during the next weekend.

**Comment by kolya-povalyaev** [comment]
Hello, thank you for your work.

**Comment by project-owner** [comment]
Hi, I've just released a new version. You can try it to see if it works now.

**Comment by kolya-povalyaev** [comment]
Hello, yes, everything worked fine, it runs even in the absence of a graphical environment.

**Comment by kolya-povalyaev** [comment]
If you write where to transfer the money, as a thank you for your help, for beer.I'll be happy to do it.

**Comment by project-owner** [comment]
Great! This is a completely free software. Adding a star to the project would be enough.
Enjoy!
