### ISSUE TITLE
Peppy Meter connected but not moving

### ISSUE THREAD

**Issue by me12ke** [project-owner/PeppyMeter.doc#2]
When I start Peppy Meter and run something via the microphone or VLC player, the Peppy Meter does not move. How can I make it move when I play something?

**Comment by project-owner** [comment]
Hi, did you install and configure the peppyalsa plugin which provides the signal for the PeppyMeter?
https://github.com/project-owner/peppyalsa.doc/wiki
https://github.com/project-owner/peppyalsa.doc/wiki/Installation
https://github.com/project-owner/peppyalsa.doc/wiki/Configuration

**Comment by me12ke** [comment]
Yes, I did, but still nothing arrives.

**Comment by project-owner** [comment]
Do you hear anything when you run VLC? How do you start VLC? Could you try to start it with the following command line parameters:
```
vlc --aout=alsa --alsa-audio-device=default YOUR_AUDIO_FILE
```
You can also try to run:
```
aplay -d default YOUR_AUDIO_FILE.wav
```
What is the output of the command:
```
aplay -l
```
What is the content of the /home/pi/.asoundrc ?

**Comment by me12ke** [comment]
When I open the VLC player via the console as you have described to me, the player opens and my music but PeppyMeter stops.

pi@raspberrypi:~ $ aplay -l
**** List of PLAYBACK Hardware Devices ****
card 0: b1 [bcm2835 HDMI 1], device 0: bcm2835 HDMI 1 [bcm2835 HDMI 1]
  Subdevices: 4/4
  Subdevice #0: subdevice #0
  Subdevice #1: subdevice #1
  Subdevice #2: subdevice #2
  Subdevice #3: subdevice #3
card 1: Headphones [bcm2835 Headphones], device 0: bcm2835 Headphones [bcm2835 Headphones]
  Subdevices: 4/4
  Subdevice #0: subdevice #0
  Subdevice #1: subdevice #1
  Subdevice #2: subdevice #2
  Subdevice #3: subdevice #3

You mean the /home/pi/Peppyalsa/asoundrc.conf or?

**Comment by project-owner** [comment]
How do you output audio? Do you use HDMI or powered speakers connected to the 3.5" audio jack?
You should have either file /home/pi/.asoundrc (for pi user) or /etc/asound.conf (for all users). Please show the one which you have. The file content described here:
https://github.com/project-owner/peppyalsa.doc/wiki/Configuration
In that file you need to specify proper 'card' and 'device' numbers. For example if you use audio output to the powered speakers (name: Headphones) you should use card 1 and device 0  in the file .asoundrc or asound.conf:
...
card 1
...
slave.pcm "hw:1,0"

**Comment by me12ke** [comment]
I output it via the 3.5 jack. I have now created and changed the .asoundrc file, but the pointer still does not move when I open VLC

**Comment by project-owner** [comment]
Do you hear the sound in speakers when you start VLC with that /home/pi/.asoundrc file?
Can you start VLC with audio file and run in a separate terminal either this command:
```
cat /home/pi/myfifo
```
or this one:
```
tail -f /home/pi/myfifo
```
Do you see anything on screen?

**Comment by me12ke** [comment]
If I try these two commands then absolutely nothing happens

**Comment by me12ke** [comment]
I've tried everything, but it never works. I open the vlc via console, nothing. I open normally, nothing. I change the .asoundrc file, nothing. I just don't know what to do next

**Comment by project-owner** [comment]
Do you hear any sound in your speakers?
If you don't see any output on screen from those commands when VLC or aplay is playing the audio file than it means that there is no signal in the named pipe /home/pi/myfifo. Which in turn means that the peppyalsa plugin was not properly installed/configured.

To make sure that it was properly installed please show the output of this command:
```
ls -l /usr/local/lib/libpeppyalsa.so
```
Also please show the content of the file /home/pi/.asoundrc.
Do you login as a 'pi' user?

**Comment by me12ke** [comment]
If I run the command, that's what I'll get out of there:
pi@raspberrypi:~ $ ls -l /usr/local/lib/libpeppyalsa.so
lrwxrwxrwx 1 root root 21 Jun 18 14:05 /usr/local/lib/libpeppyalsa.so -> libpeppyalsa.so.0.0.0

Yes, I log in normally as a PI user. I think it's because of the .asoundrc file, because I don't find this file under / home / pi but in the Peppyalsa folder and there in a folder called alsa-config and the file is also called asound.conf ud not .asoundrc but it says it same inside.

**Comment by project-owner** [comment]
Please create the file /home/pi/.asoundrc with the content described here:
https://github.com/project-owner/peppyalsa.doc/wiki/Configuration
Make sure that the file has a dot in the name. To see such files run the list command with 'a' option:
ls -la
Don't forget to specify in that file the correct card and device numbers as was described above.

**Comment by me12ke** [comment]
I have just executed the command ls -la and see that there is an .asoundrc file, but it is not displayed in the file manager.

**Comment by me12ke** [comment]
I found the .asoundrc file, it was just hidden. I also did the configuration, but I still get sound, but the meter still doesn't move.

**Comment by project-owner** [comment]
Do you have the named pipe /home/pi/myfifo ? You can check that by running the command: 
```
ls /home/pi
```
If you have it just remove it:
```
rm /home/pi/myfifo
```
Then start VLC again and after check that the file was created again:
```
ls /home/pi
```
If you will see the named pipe that means that peppyalsa plugin works fine. While running VLC try to use those 'cat' or 'tail' commands described earlier to see if there is data in the pipe. I still suspect there is some misconfiguration.

**Comment by me12ke** [comment]
I've deleted it now, but he didn't recreate it

**Comment by project-owner** [comment]
This is wrong, if the named pipe /home/pi/myfifo was deleted it should be created every time you start a playback.
Please show me the content of the file /home/pi/.asoundrc
Can you play any WAV file this way?
```
aplay --device=default some_file.wav
```
and run the following command in another terminal:
```
cat /home/pi/myfifo
```
The PeppyMeter will not work until you see the output on screen from the 'cat' command. That will prove that there is data in the named pipe (/home/pi/myfifo).

**Comment by me12ke** [comment]
OK. I've now deleted the myfifo and then ran a wav file, but it still doesn't create a new one. How do I get it now that it is automatically recreated?

**Comment by project-owner** [comment]
If peppyalsa plugin was compiled and installed properly it should create new named pipe (/home/pi/myfifo) automatically when you start playing audio file.
Please show me the content of the file /home/pi/.asoundrc

**Comment by me12ke** [comment]
This is the content of the .asoundrc file:

`pcm.!default {
        type plug
        slave.pcm "softvol_and_peppyalsa"


ctl.!default {
        type hw
        card 1
}

pcm.peppyalsa {
        type meter
        slave.pcm "hw:1,0"
        scopes.0 peppyalsa
}

pcm.softvol_and_peppyalsa {
        type softvol
        slave.pcm "peppyalsa"
        control {
                name "PCM"
                card 0
        }
}

pcm_scope.peppyalsa {
        type peppyalsa
        decay_ms 400
        meter "/home/pi/myfifo"
        meter_max 100
        meter_show 0
        spectrum "/home/pi/myfifosa"
        spectrum_max 100
        spectrum_size 30
}

pcm_scope_type.peppyalsa {
        lib /usr/local/lib/libpeppyalsa.so
}

pcm.dsp0 peppyalsa
`

**Comment by project-owner** [comment]
I hope you don't use the single quotes in the file.
It should be card 1 everywhere.

**Comment by me12ke** [comment]
Yes, but it doesn't work even if I set the card to 1

**Comment by project-owner** [comment]
Weird, everything looks OK but not working. Which OS do you use?
Did you have /home/pi/myfifo before? If so, that means that peppyalsa plugin was working at some point if you didn't create the pipe manually.

**Comment by me12ke** [comment]
I have the Raspberry Pi OS with the bit variant. Of course, it could be because it doesn't work. I don't know if I had it before the installation. I honestly didn't pay attention.

**Comment by me12ke** [comment]
Correction: I have the 64 bit variant, maybe I should try the 32 bit variant?

**Comment by project-owner** [comment]
I've never tried 64-bit OS version. I'm not sure if that can be the reason.
Do you use the version with Desktop? As far as I know the desktop version has PulseAudio on top of the ALSA. That could affect the meter. I don't use the desktop OS in my projects. I use the lite/headless version.
One user reported today that PeppyMeter works fine: https://github.com/project-owner/PeppyMeter.doc/issues/3
So more likely it's not the meter issue but environment or configuration issue.

**Comment by me12ke** [comment]
Oh okay. I had now used the desktop version, just for the reason because I'm not experienced sooo with Linux systems. I have 2 Raspberry Pi Maybe I'll try with a just the Lite version.

**Comment by project-owner** [comment]
You can try to use 32-bit version first and see if it works.
With Lite version you should know how to connect display as the meter doesn't work in a terminal.
The easiest way is to install the Peppy Player using one of the images for your display:
https://github.com/project-owner/PeppyPlayers.doc/wiki/Disk-Images
When you see that meter screensaver works you can get rid of Peppy player and install PeppyMeter.
