### ISSUE TITLE
run maximized at startup

### ISSUE THREAD

**Issue by tester1969** [project-owner/PeppyMeter.doc#3]
Hi I can run it command line. I have a couple of questions:

1. Can I run input from USB sound card? Should I run vlc or something for this or i can just declare the device somehow?
OK, I declared in .asound.rc the device and speaker-test makes the needle move. Now I need to give input to sound card to see what happens
2. How this can run maximized at startup?

**Comment by tester1969** [comment]
OK found I have to put it in lxsession autostart but still have issue:

`pygame 1.9.4.post1
Hello from the pygame community. https://www.pygame.org/contribute.html
Traceback (most recent call last):
  File "/home/pi/PeppyMeter/peppymeter.py", line 236, in <module>
    pm = Peppymeter(standalone=True)
  File "/home/pi/PeppyMeter/peppymeter.py", line 60, in __init__
    parser = ConfigFileParser(base_path)
  File "/home/pi/PeppyMeter/configfileparser.py", line 145, in __init__
    self.meter_config[METER] = c.get(CURRENT, METER)
  File "/usr/lib/python3.7/configparser.py", line 780, in get
    d = self._unify_values(section, vars)
  File "/usr/lib/python3.7/configparser.py", line 1146, in _unify_values
    raise NoSectionError(section) from None
configparser.NoSectionError: No section: 'current'
** Message: 13:55:15.005: app.vala:130: /usr/bin/python3 exit with this type of exit: 256
`

**Comment by project-owner** [comment]
I'm glad that you made it working. Another way to solve that startup problem could be to run this command in your script before starting the meter: 'cd /home/pi/PeppyMeter'.

**Comment by tester1969** [comment]
I did that but it didn't work :(
Anyway now it is exactly as I wanted it to be. I want to try the options to see if it can play more smoothly. However it is fantastic. I have built monoblocks and have put a 7" screen in face, which now shows vumeter. Screen is touch. I want to make it when it touches the screen to recycle meters. I am also working the other sensors

**Comment by project-owner** [comment]
I can probably add the new meter type - 'touch'. Please let me know if you will share your project on any forum or social media. Thanks!

**Comment by tester1969** [comment]
If you add it it would be fine. But I don't post anywhere, I am really lazy doing writeups and stuff.
