### ISSUE TITLE
Peppymeter error at run peppymeter.py

### ISSUE THREAD

**Issue by marcocand** [project-owner/PeppyMeter.doc#4]
HI,

I've used successfully peppymeter in the past.

I'm now trying to make a new installation to use it again. Last time I've taken lots of note so I've used the same note to
install again peppymeter from scratch. I'm using raspberry pi 3b as in the past. Running installation I'm not getting any
errors. When I run again the peppymeter.py from Tony Phyton IDE I'm getting the following errors;

>>> %Run peppymeter.py
pygame 1.9.4.post1
Hello from the pygame community. https://www.pygame.org/contribute.html
Traceback (most recent call last):
  File "/home/pi/PeppyMeter/peppymeter.py", line 271, in <module>
    pm = Peppymeter(standalone=True)
  File "/home/pi/PeppyMeter/peppymeter.py", line 61, in __init__
    parser = ConfigFileParser(base_path)
  File "/home/pi/PeppyMeter/configfileparser.py", line 159, in __init__
    self.meter_config[METER] = c.get(CURRENT, METER)
  File "/usr/lib/python3.7/configparser.py", line 780, in get
    d = self._unify_values(section, vars)
  File "/usr/lib/python3.7/configparser.py", line 1146, in _unify_values
    raise NoSectionError(section) from None
configparser.NoSectionError: No section: 'current'
>>> 

and the peppymeter does not appear on my pi 7inch display.

I do not see any possible cause.

Do you have any suggestions?

Many thanks in advance.

Bye!

**Comment by project-owner** [comment]
Hi marcocand,

Usually this error happens when you start the program from the folder other than /home/pi/PeppyMeter. For example you will get this exception when you start it from the folder /home/pi. Please make sure that you start it from the folder  /home/pi/PeppyMeter.

Best regards

**Comment by marcocand** [comment]
Hi,

many thanks this way it work!

Bye!

**Comment by marcocand** [comment]
Really fast and very kind of you...
