### ISSUE TITLE
PeppyMeter always full scale

### ISSUE THREAD

**Issue by marcocand** [project-owner/PeppyMeter.doc#5]
Hi,

after running 

cd PeppyMeter
phython3 peppymeter.py

the meters starts correctly.

As soon as I run

aplay -D peppyalsa ride.mp3

the meters are going full scale and I'm getting lots of white noise on my loud speaker, I've increase the amixer volume, selected
di right audio output but same results.

Any possible causes?

Many thanks in advance.

Bye!

Marco Italy.

**Comment by project-owner** [comment]
Hi Marco,

Can you play it without peppyalsa? I'm not sure if aplay can play mp3 files. Can you try WAV file?
What is the output of the command:
```
aplay -l
```

Best regards
