### ISSUE TITLE
Peppy Meter Vertical Bar audio analyzer bit map

### ISSUE THREAD

**Issue by marcocand** [project-owner/PeppyMeter.doc#6]
Hi,

I working around Peppy Meter, let me to write the existent meters windows are great.
By the way I've seen some were you were explaining Vertical Bars Audio Spectrum analyzer.
Looking on the downloaded file I do not see anything like that.

Do you have it?

Many thanks in advance.

Bye!

Marco from Italy.

**Comment by project-owner** [comment]
Hi Marco,

PeppyMeter doesn't show Spectrum Analyzer. It shows only VU Meter.
Though the peppyalsa plugin which is used by the PeppyMeter can output spectrum data as well:
https://github.com/project-owner/peppyalsa.doc/wiki

The Peppy Player has a Spectrum Analyzer screensaver:
https://github.com/project-owner/Peppy.doc/wiki/Spectrum-Analyzer
I'm planning to make a stand-alone Spectrum Analyzer. Though I'm not sure when.

Best regards

**Comment by project-owner** [comment]
I've recently released PeppySpectrum as a stand-alone spectrum analyzer:
https://github.com/project-owner/PeppySpectrum.doc/wiki
