### ISSUE TITLE
Error "undefined symbol"

### ISSUE THREAD

**Issue by TheRealOtto** [project-owner/PeppyMeter.doc#7]
I installed PeppyMeter on a Raspberry Pi 4 with 3.5" Display.
Now when I start peppymeter.py, following error is displayed:

ImportError: /home/pi/.local/lib/python3.9/site-packages/pygame/rwobject.cpython-39-arm-linux-gnueabihf.so: undefined symbol: SDL_RWclose

I could not find a way to solve this problem on the web.

**Comment by project-owner** [comment]
Hi,

Here is what I found on web:
https://www.gitmemory.com/issue/pygame/pygame/2657/891780324
It looks like you faced the same issue. Please try to follow the recommendations on that page. One of them is to use Python 3.7.

Best regards

**Comment by TheRealOtto** [comment]
Thank you for this info.
I am actually using Python 3.7.

The strange thing is: 
If I install pygame with apt (apt install python3-pygame), version 1.9.xx will be installed in "/usr/lib/python3/dist-packages/pygame", but Python does not find it with "import pygame".

If I install it with pip (pip3 install pygame), version 2.0.1 will be installed in a new directory "/home/pi/.local/lib/python3.9/site-packages/pygame". Python finds it although I have no Python 3.9 installed, but I get the error message.

I guess I have to try to get an older version of the pygame wheel.

Thanks again!

**Comment by project-owner** [comment]
You can also try to install the older version of pygame:
pip3 install pygame==1.9.4

**Comment by TheRealOtto** [comment]
I decided to set up the system again from scratch.

**Comment by TheRealOtto** [comment]
Problem solved!
With a clean new installation I got PeppyMeter running.
For now just with "noise", but will try the pipe tomorrow.

By the way, is there a way to show the meter in full screen? no.frame still shows the taskbar.

**Comment by project-owner** [comment]
Do you use the OS with Desktop or without? In the OS with desktop no.frame can control only the PeppyMeter window frame.

**Comment by TheRealOtto** [comment]
OK, thanks.
The next install will be without desktop!
