### ISSUE TITLE
PeppyMeter config.txt for HDMI display

### ISSUE THREAD

**Issue by TheRealOtto** [project-owner/PeppyMeter.doc#8]
After getting PeppyMeter to run successfully on my Raspberry Pi 4 with a 3.5" display (attached to GPIO), I tried to run it on a Raspberry Pi Zero W with a HDMI display (waveshare 1024x600).

But after starting peppymeter.py, there is the pygame-error message: 
"peppymetr.py", line 150, in init_display, pygame.display.init()
pygame error: unable to open /dev/fb1

So I changed /dev/fb1 to /dev/fb0 in config.txt. The next error was:
pygame error: unable to open mouse

Could you please guide me to how to change the [sdl.env] section in config.txt to get peppymeter running?

Thank you

**Comment by project-owner** [comment]
Try to disable the double buffering
```
double.buffer = False
```

**Comment by TheRealOtto** [comment]
Yes, that did the trick. Now it runs.
By the way, great support from your side. Thanks
